label.titulo.pagina.consulta.agenda=Agendas Cadastradas
label.titulo.pagina.cadastro.agenda=Cadastro de Agenda
label.titulo.pagina.edicao.agenda=Editar Agenda
label.nome.agenda=Nome da Agenda
label.periodo.disponivel=Período Disponível
label.novo.agenda=Nova Agenda
label.modal.corpo.agenda=Deseja realizar a exclusão da agenda?
label.periodo.manha=Manhã
label.periodo.tarde=Tarde
label.periodo.ambos=Ambos