label.titulo.pagina.consulta.compromisso=Compromissos Agendados
label.titulo.pagina.cadastro.compromisso=Novo Compromisso
label.titulo.pagina.edicao.compromisso=Editar Compromisso
label.novo.compromisso=Novo Compromisso
label.modal.corpo.compromisso=Deseja realizar a exclusão do compromisso?