label.titulo.pagina.consulta=Funcionários Cadastrados
label.titulo.pagina.cadastro=Cadastro de Funcionário
label.titulo.pagina.edicao=Editar Funcionário
label.titulo.pagina.novo=Novo Funcionário
label.modal.corpo=Deseja realmente realizar a exclusão do funcionário?