label.titulo.pagina=Avaliação Ager
label.novo=Novo
label.excluir=Excluir
label.editar=Editar
label.salvar=Salvar
label.cancelar=Cancelar
label.acao=Ação
label.id=Código
label.nome=Nome
label.buscar.por=Buscar Por
label.pesquisar=Pesquisar
label.escolha=Escolha...
label.sim=Sim
label.nao=Não
label.limpar.formulario=Limpar Formulário


label.funcionario=Funcionário
label.agenda=Agenda
label.compromisso=Compromisso
label.data=Data
label.hora=Hora
label.id.funcionario=Cód. Funcionário
label.id.agenda=Cód. Agenda


label.menu.funcionarios=Funcionários
label.menu.agendas=Agendas
label.menu.compromissos=Compromissos
label.menu.relatorio=Relatório


salvar.sucesso=Registro salvo com sucesso!
alterar.sucesso=Registro alterado com sucesso!
excluir.sucesso=Registro excluído com sucesso!
salvar.erro=Ocorreu um erro ao tentar salvar o registro.
alterar.erro=Ocorreu um erro ao tentar alterar o registro.
excluir.erro=Ocorreu um erro ao tentar excluir o registro.


label.modal.titulo=Confirmação de Exclusão